<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SVRODK00070" ignored="0" name="Regression suite 1" tests="5" failures="1" timestamp="23 Jul 2018 14:36:09 GMT" time="56.576" errors="0">
  <testcase name="testContactUs" time="1.705" classname="group1.artifact2.Test.ContactUsTest"/>
  <testcase name="testLogIn" time="5.535" classname="group1.artifact2.Test.LogInTest"/>
  <testcase name="testCart" time="6.977" classname="group1.artifact2.Test.CartTest"/>
  <testcase name="testSearch" time="1.644" classname="group1.artifact2.Test.SearchTest"/>
  <testcase name="testHome" time="3.217" classname="group1.artifact2.Test.HomeTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at group1.artifact2.Test.HomeTest.testHome(HomeTest.java:21)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testHome -->
</testsuite> <!-- Regression suite 1 -->
